### ISSUE TITLE
manage errors in shiny part

### ISSUE THREAD

**Issue by aitmlouk** [mhahsler/arulesViz#11]
Hi Michael Hahslern,
thank you for your efforts to make association rules algorithms available in R with rich visualization techniques.
I used Arules and ArulViz packages many times and as I developed many shiny apps for the research tasks I faced some errors in my shiny interfaces related to the error management methods in arulesviz package the first is when there are no rules for selected itemsets, it return a stop message like this (x contains 0 rules!) for user experience is not good to show this red error especially it appear like (error:x contains 0 rules!)
`if(length(x)<1) stop("x contains 0 rules!")`
Maybe it will be good if it appears like this
`validate(
  need(length(x)>1, "x contains 0 rules!")
)`
or 
`if (length(x)<1) {
     "x contains 0 rules!"
  }`

**Comment by mhahsler** [comment]
Hi aitmlouk,

Sorry for the late reply! The plot functions in arulesViz cannot contain shiny specific code like `validate`. arulesViz comes with a shiny app called ruleExplorer. It deals with errors gracefully. I use in the app code the following:

      handleErrors <- shiny::reactive({
        shiny::validate(
          shiny::need(length(rules())>0, 'No rules to visualize! Decrease support, confidence or lift.')
        )
      })

Have a look at the source code and let me know if this does not solve your issues.

Regards,
Michael
