### ISSUE TITLE
Is there anyway to use arulesViz to visualize itemsets returned by opusminer?

### ISSUE THREAD

**Issue by nchelaru** [mhahsler/arulesViz#13]
Hello!

First of all, thank you so much for making `arulesViz`, it is a great package!

I know that I can use `arulesViz` to visualize itemsets returned by `arules`, but I'm wondering if I can make the same visualizations with itemsets returned by the `opusminer` package? From what I can see, `opusminer` returns list of itemsets quite similar in format to that returned by `generatingItemsets(rules)`, but without the support parameter for each. 

Thank you very much for any help!

**Comment by mhahsler** [comment]
I just looked at opusminer. If the itemsets have no support then you can calculate it from the data using code like:

    quality(your_itemsets) <- interestMeasure(your_itemsets, transactions = your_trans)

Now the visualization should work.
