### ISSUE TITLE
Use par settings, xlab&ylab

### ISSUE THREAD

**Issue by Derek-Jones** [mhahsler/arulesViz#15]
`plot.rules` should use the current values set by calls to the `par` function, e.g., `bty` and `cex`.

Also being able to specify `xlab` and `ylab` (if only to make the first letter upper case, to be consistent with other plots).

**Comment by mhahsler** [comment]
That depends on the plotting engine. The default engine has been `grid` which does not use par, but its own version. Some plots have the engine = 'base' available, which uses the set values from par.

arulesViz will switch the default engine to ggplot2 In the next release.

**Comment by Derek-Jones** [comment]
Ok, a different plotting engine (is this specified in the help page, I did not look).

But at least allow xlab and ylab to be specified.

**Comment by mhahsler** [comment]
Yes, starting with arulesViz version 1.4-0, there are different engines and the man page talks about this. The man page could always be better, though.

You can specify xlab and ylab, you just need to do it in the right way depending on the engine. I will add some more examples to the man page to show how that can be done.
