### ISSUE TITLE
Data table contains several rows but none are displayed

### ISSUE THREAD

**Issue by PetrellisKostas** [mhahsler/arulesViz#17]
Using ruleExplorer function the data table does not display any row.
![image](https://user-images.githubusercontent.com/48026178/84379342-554e9180-abee-11ea-8dcf-90cb6584bfe6.png)

**Comment by Delvis** [comment]
Yes, just noticed that inspectDT doesn't work anymore within shiny (some conflict with more recent version of shiny or DT packages, maybe?)

**Comment by hoangthongtran412** [comment]
I also face the similar issues.

1. inspectDT() produces Javascript Alert _"DataTables warning table id=datatables_table_0 - requested unknown parameter '8' for row 0 column 8_." but still able to display table results.
2. ruleExplorer() fails to display table results.

Please help resolve them.

**Comment by Fpadt** [comment]
Same issue here. However it does work on older R-version. 

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo   



![Snag_38e384ae](https://user-images.githubusercontent.com/4258894/105012509-8291d680-5a3e-11eb-80aa-fdefa3a000a2.png)

**Packages**
arulesViz: 1.3-3
arules: 1.6-5
shiny 1.3.2
shinythemes 1.1.2

`data("Groceries");  
rules <- apriori(Groceries, parameter=list(support=0.001, confidence=0.8));  
ruleExplorer(rules)`

**Comment by mhahsler** [comment]
Thanks for the report and sorry for the delay. This bug is confirmed.

**Comment by mhahsler** [comment]
The bug is now fixed in the development version on GitHub. The fix will be part of the next release.
