### ISSUE TITLE
Set Color Limit

### ISSUE THREAD

**Issue by ghost** [mhahsler/arulesViz#18]
Is there a way to set a limit to the color grade?

Suppose that I have 1 rule with Lift 4 but all the other around 0.7 - 1.3. I would like to display the color grade in the range 0.7-1.3.

**Comment by mhahsler** [comment]
That depends on the plot method and used engine. Here is an example for the engine grid where I use zlim to limit the color.

plot(rules, method = "scatter", engine = "grid", control = list(zlim = c(0,2)), verbose = TRUE)

For engine ggplot2 you would need to add a  new scale with `+`.
