### ISSUE TITLE
hclust fails w/o minimum number of clusters

### ISSUE THREAD

**Issue by gdbassett** [mhahsler/arulesViz#2]
line
`km <- cutree(hclust(dist(s_clust)), h=0)`
fails with error
 `Error in hclust(dist(s_clust)) : must have n >= 2 objects to cluster`
when a minimum number of rules are not available.

We run arules in an iterative script generating knitr reports and so sometimes the cut of the data simply isn't enough.  Currently we just catch the error and fall back to `inspect(rules)`, but it may make sense for the package to catch the error if there are less than 2 rules.

**Comment by mhahsler** [comment]
It seems like `hclust` produces the error message. `hclust` is not part of the arules or arulesViz package so I cannot add code to catch this problem.
