### ISSUE TITLE
Available methods limited to: ‘graph’, ‘paracoord’, ‘scatterplot’

### ISSUE THREAD

**Issue by nise** [mhahsler/arulesViz#6]
I have installed version 1.3 but cannot use methods other than ‘graph’, ‘paracoord’, and ‘scatterplot’. 

> plot(fsets, method="matrix")
> Error in plot.itemsets(fsets, method = "matrix") : 
>   Unknown method: ‘matrix’ 
> Available methods: ‘graph’, ‘paracoord’, ‘scatterplot’ 

System info:
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

**Comment by nise** [comment]
I found the reason for this behavior. When using Eclat for itemset mining arulesViz only provides the methods ‘graph’, ‘paracoord’, and ‘scatterplot’. Apriori instaed, provides the full range for methods as documented in the manual. 
I would suggest to improve the error message and explain why certain visualization cannot be plotted.

**Comment by mhahsler** [comment]
You provide itemsets and for these not all methods are available. I have added a sentence to the man page.
