### ISSUE TITLE
Unable to Load into R

### ISSUE THREAD

**Issue by LuckyDao** [mhahsler/arulesViz#8]
Hello,

**install.packages doesn't seem to load in all the required dependencies:**
install.packages("arulesViz",dependencies = TRUE)
library(arulesViz)

**throws error**:
Loading required package: grid
Error: package or namespace load failed for ‘arulesViz’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘iterators’

**I _think_ some dependencies are missing, but I'm not too good at this yet:**
if I manually install these:  (grid, iterators, fpc), library(arulesViz) will no longer throw an error.

Thanks for your work and your time

**Comment by mhahsler** [comment]
Thanks for letting me know.

arulesViz itself does not use iterators, but it relies on the packages seriation, which uses TSP, which uses foreach which ends up using iterators. I suspect that either your R or one of the packages in this chain was not up-to-date.
